
# Load required libraries
library(dplyr)
library(ComplexHeatmap)

# Load the "sc" object generated by RaceID in the "Dimensionality_reduction_and_clustering_RaceID.R"  script

# Retrieve the features selected by RaceID algorithm
features <-  sc@cluster$features

# Removing the clusters with less or equal to 10 cells
table(sc@cpart)
# Clusters to remove: 19, 20, 21, 22, 24, 26, 27
clustersTokeep <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,23,25)
clustersVector <- vector()
for (i in 1:length(sc@cpart)) {
  if (sc@cpart[i] %in% clustersTokeep) {
    clustersVector <- c(clustersVector, sc@cpart[i])
  }
}

clusters <- as.data.frame(sc@cpart)
clusters$cell <- rownames(clusters)
colnames(clusters) <- c("cluster", "cell")
clusters <- clusters[rownames(clusters) %in% names(clustersVector), ]

clusters <- arrange_all(clusters, by_group = clusters)
rownames(clusters) <- clusters$cell

# Define the cluster annotations and colors
column_ha2 = HeatmapAnnotation(cluster= clusters$cluster, col = list(cluster = c("1" = sc@fcol[1], "2" = sc@fcol[2],
                                                                                 "3" = sc@fcol[3], "4" = sc@fcol[4],
                                                                                 "5" = sc@fcol[5], "6" = sc@fcol[6],
                                                                                 "7" = sc@fcol[7], "8" = sc@fcol[8],
                                                                                 "9" = sc@fcol[9], "10" = sc@fcol[10],
                                                                                 "11" = sc@fcol[11], "12" = sc@fcol[12],
                                                                                 "13" = sc@fcol[13], "14" = sc@fcol[14],
                                                                                 "15" = sc@fcol[15], "16" = sc@fcol[16],
                                                                                 "17" = sc@fcol[17], "18" = sc@fcol[18],
                                                                                 "23" = sc@fcol[23], "25" = sc@fcol[25]))) 


# Provide the scaled data set with the HVG (features selected by RaceID)
data3 <- as.matrix(sc@ndata)
dim(data3)
data3_zsc <- t(as.data.frame((scale(t(data3)))))


# Plot the heatmap of HVGs
set.seed(1500)
Heatmap(data3_zsc[sc@cluster$features, rownames(clusters)], 
        show_row_names = F, 
        row_title = NULL, 
        column_title_side = "top", 
        show_heatmap_legend = T, 
        name = "zscore", 
        top_annotation = column_ha2,
        cluster_columns = cluster_within_group(data3_zsc[ sc@cluster$features, rownames(clusters)],  clusters$cluster),
        row_names_gp = gpar(fontsize = 11),
        border = T,
        show_column_names = F, 
        column_split =  20, 
        cluster_column_slices = T, 
        show_row_dend = F)



################# Plotting the markers used in the initial classification of the clusters  ###################
# Define the markers:
markers <- c(
  NSCs <- c("Aldoc", "Apoe", "Id4", "Hopx", 
            "Sox9", "Slc1a3", "Sox2"),
  IPCs <- "Eomes",
  
  CajRet <- c("Reln", "Trp73"), 
  
  Perc <- c("Vtn", "Ifitm1"), 
  
  RedBC <- c("Hbb-bs", "Hbb-bt", "Hba-a1"),
  
  IN <- c("Gad1", "Arx"),
  
  CortHem <- c("Wnt8b", "Rspo1", "Rspo2", "Lmx1a"), 
  
  "Pou3f1",
  
  CA3 <- "Grik4",
  
  "Tbr1",
  "Bcl11b",
  "Hes5",
  "Neurod1",
  "Neurod2",
  "Dcx",
  "Tubb3",
  
  DGprecur <- c("Neurog2", "Prox1"), 
  
  "Ldb2")


# Filter the data set with the defined markers
data3 <- data3[markers , ]
dim(data3)

data3_zsc <- t(as.data.frame((scale(t(data3)))))


# Plot the heatmap of marker genes
set.seed(1500)
Heatmap(data3_zsc[ , rownames(clusters)], 
        show_row_names = T, 
        row_title = NULL, 
        column_title_side = "top", 
        show_heatmap_legend = T, 
        name = "zscore", 
        top_annotation = column_ha2,
        row_names_gp = gpar(fontsize = 11),
        border = T,
        show_column_names = F, 
        column_split =  clusters$cluster,
        cluster_column_slices = F, 
        show_row_dend = F,
        show_column_dend = F)
