

###########    DPT Analysis of the hippocampal lineage - related cell populations  #######################

# Use as input for the analysis the "sc" object generated by the RaceID (version 0.1.3) algorithm in the previous analysis steps

# Load some metadata information
meta_data_sc <- readRDS("~/Downloads/metadata_sc.RDS")

library(SingleCellExperiment)
library(destiny)

# Converting the expdata and ndata slots from the RaceID to matrices so I can populate the SCE object
sc_mat <- as.matrix(sc@expdata)
sc_mat <- sc_mat[ , colnames(sc@ndata)]

# Defining the cells from the "sc" object that will be filtered: 
fdClust <- c( cellsC14 <- names(sc@cpart[sc@cpart == 14]), # interneurons
              cellsC15 <- names(sc@cpart[sc@cpart == 15]), # red blood cells
              cellsC19 <- names(sc@cpart[sc@cpart == 19]), # OPCs
              cellsC16 <- names(sc@cpart[sc@cpart == 16]), # Pericytes
              cellsC17 <- names(sc@cpart[sc@cpart == 17]), # Unknown
              cellsC24 <- names(sc@cpart[sc@cpart == 24]), # Choroid plexus
              cellsC26 <- names(sc@cpart[sc@cpart == 26]), # Microglia
              cellsC27 <- names(sc@cpart[sc@cpart == 27]), # Unknown 1 cell
              cellsC22 <- names(sc@cpart[sc@cpart == 22]), # Unknown 1 cell
              cellsC21 <- names(sc@cpart[sc@cpart == 21]), # Unknown 10 cells
              
              cellsC7 <- names(sc@cpart[sc@cpart == 7]), # CR1
              cellsC25 <- names(sc@cpart[sc@cpart == 25]), # CR2
              cellsC10 <- names(sc@cpart[sc@cpart == 10]), # CR3
              cellsC20 <- names(sc@cpart[sc@cpart == 20]), # CR4
              
              
              cellsC6 <- names(sc@cpart[sc@cpart == 6]), # Subc1
              cellsC13 <- names(sc@cpart[sc@cpart == 13]) # Subc2
              
)

# Filtering the matrix
mat <- sc_mat[ , !colnames(sc_mat) %in% fdClust]
dim(mat)

# Initializing the Expression set object
sce <- as.ExpressionSet(as.data.frame(t(mat)))
sce

# Add the metadata:
rownames(meta_data_sc) <- meta_data_sc$cell
clusters <- meta_data_sc[colnames(mat) , 4] 
clusters <- as.character(clusters)
clusters <- as.factor(clusters)

clusters_ext <- meta_data_sc[colnames(mat), 6] 
clusters_ext <- as.character(clusters_ext)
clusters_ext <- as.factor(clusters_ext)

condition <- substr(colnames(mat), start = 0, stop = 4)
condition <- as.factor(condition)
condition2 <- as.factor(substr(colnames(mat), start = 0, stop = 3))

phenoData(sce)$clusters <- clusters
phenoData(sce)$clusters_ext <- clusters_ext
phenoData(sce)$condition <- condition
phenoData(sce)$condition2 <- condition2

# Computing the diffusion map analysis on the sce object
# Find the sigmas and check for the optimal value
set.seed(12345)
sigmas <- find_sigmas(sce, verbose = TRUE)
optimal_sigma(sigmas)

# Finding the knns
find_dm_k((nrow(mat)-1), min_k = 100L, small = 1000L, big = 10000L)

# Compute the diffusion map with the fine tunned parameters
dm <-DiffusionMap(sce, verbose= TRUE, sigma = sigmas, k =100)
plot(dm, 1:2)

# Creating a diffusion pseudo time object from the diffusion map object
dpt <- DPT(dm)
plot(dpt)

# Plot with DPT with different roots for checking the correct starting point based on previous knowledge
plot(dpt, root= 1)
plot(dpt, root= 2)
plot(dpt, root= 3)


##########################################################################################################
###########  RUNNING FATEID ON THE DPT CELLS ORDERING  ###################################################
#########################################################################################################

library(RaceID)
library(FateID)

# Extract the ordering of the cells based on the DPT and the tip
order_tip_2 <- order(dpt[tips(dpt)[[2]], ])
exprs <- Biobase::exprs(sce)
# Change the order of the cells as the DPT arrangement
exprs_subset <- exprs[ , order_tip_2]
n <- colnames(exprs_subset)
# Get the filtered data
x <- getfdata(sc, n = n)
dim(x)
# Perform the SOM analysis
fs  <- filterset(x,n=n)
s1d <- getsom(fs,nb=1000,alpha=.5)
ps  <- procsom(s1d,corthr=.85,minsom=3)
y    <- sc@cpart[n]
fcol <- sc@fcol


# Plot the heatmap of the gene Nodes along the DPT
set.seed(1234)
plotheatmap(ps$all.z,xpart=y,xcol=fcol,ypart=ps$nodes,xgrid=FALSE,ygrid=TRUE,xlab=FALSE)


########################################################################################################
################  Over-representation test for exemplary Nodes retrieved by FATEID #####################
########################################################################################################
library(org.Mm.eg.db)
library(clusterProfiler)

# NODE 2
g <- names(ps$nodes)[ps$nodes == 2]
plotexpression(fs,y,g,n,col=fcol,name="Node 2",cluster=FALSE,alpha=.5,types=NULL,cex = 0.5)


Allgenes <- rownames(fs)
names(Allgenes) <- Allgenes

genesN2 <- names(ps$nodes)[ps$nodes == 2]
names(genesN2) <- genesN2

egoN2 <- enrichGO(gene = names(genesN2), universe = names(Allgenes), 
                  OrgDb = org.Mm.eg.db, ont = "BP", 
                  pAdjustMethod = "BH", pvalueCutoff = 0.05, 
                  qvalueCutoff = 0.05, minGSSize = 10, 
                  maxGSSize = 500, keyType = "SYMBOL")


#  NODE 9
g <- names(ps$nodes)[ps$nodes == 9]
plotexpression(fs,y,g,n,col=fcol,name="Node 9",cluster=FALSE,alpha=.5,types=NULL,cex = 0.5)

Allgenes <- rownames(fs)
names(Allgenes) <- Allgenes

genesN9 <- names(ps$nodes)[ps$nodes == 9]
names(genesN9) <- genesN9

egoN9 <- enrichGO(gene = names(genesN9), universe = names(Allgenes), 
                  OrgDb = org.Mm.eg.db, ont = "BP", 
                  pAdjustMethod = "BH", pvalueCutoff = 0.05, 
                  qvalueCutoff = 0.05, minGSSize = 10, 
                  maxGSSize = 500, keyType = "SYMBOL")


#  NODE 25
g <- names(ps$nodes)[ps$nodes == 25]
plotexpression(fs,y,g,n,col=fcol,name="Node 25",cluster=FALSE,alpha=.5,types=NULL,cex = 0.7)

Allgenes <- rownames(fs)
names(Allgenes) <- Allgenes

genesN25 <- names(ps$nodes)[ps$nodes == 25]
names(genesN25) <- genesN25

egoN25 <- enrichGO(gene = names(genesN25), universe = names(Allgenes), 
                   OrgDb = org.Mm.eg.db, ont = "BP", 
                   pAdjustMethod = "BH", pvalueCutoff = 0.05, 
                   qvalueCutoff = 0.05, minGSSize = 10, 
                   maxGSSize = 500, keyType = "SYMBOL")


#  NODE 26
g <- names(ps$nodes)[ps$nodes == 26]
plotexpression(fs,y,g,n,col=fcol,name="Node 26",cluster=FALSE,alpha=.5,types=NULL,cex = 0.7)

Allgenes <- rownames(fs)
names(Allgenes) <- Allgenes

genesN26 <- names(ps$nodes)[ps$nodes == 26]
names(genesN26) <- genesN26

egoN26 <- enrichGO(gene = names(genesN26), universe = names(Allgenes), 
                   OrgDb = org.Mm.eg.db, ont = "BP", 
                   pAdjustMethod = "BH", pvalueCutoff = 0.05, 
                   qvalueCutoff = 0.05, minGSSize = 10, 
                   maxGSSize = 500, keyType = "SYMBOL")


#  NODE 28
g <- names(ps$nodes)[ps$nodes == 28]
plotexpression(fs,y,g,n,col=fcol,name="Node 28",cluster=FALSE,alpha=.5,types=NULL,cex = 0.7)

Allgenes <- rownames(fs)
names(Allgenes) <- Allgenes

genesN28 <- names(ps$nodes)[ps$nodes == 28]
names(genesN28) <- genesN28

egoN28 <- enrichGO(gene = names(genesN28), universe = names(Allgenes), 
                   OrgDb = org.Mm.eg.db, ont = "BP", 
                   pAdjustMethod = "BH", pvalueCutoff = 0.05, 
                   qvalueCutoff = 0.05, minGSSize = 10, 
                   maxGSSize = 500, keyType = "SYMBOL")


######### Generate Barplots for representing the distinct GO termns
library(ggplot2)

# Node #2
# 8 GO terms
data1 <- egoN2@result[1:8, ]
data1$order <- c(1:length(data1$ID))
ggplot(data1, aes(x = order, y = Count, fill = p.adjust)) + 
  geom_bar(stat = "identity") +
  geom_text(aes(label = Description, y = 1), hjust=0, vjust= 0.5, size= 6) +
  coord_flip()  + 
  theme_classic() +
  scale_fill_gradient(low = "orange", high = "royalblue") + 
  theme(axis.title.y = element_blank(), axis.text.y = element_blank(), axis.ticks.y = element_blank()) +
  scale_y_continuous(expand = c(0,0)) 

# Node #9
# 6 GO terms
data1 <- egoN9@result[1:6, ]
data1$order <- c(1:length(data1$ID))
ggplot(data1, aes(x = order, y = Count, fill = p.adjust)) + 
  geom_bar(stat = "identity") +
  geom_text(aes(label = Description, y = 1), hjust=0, vjust= 0.5, size= 6) +
  coord_flip()  + 
  theme_classic() +
  scale_fill_gradient(low = "orange", high = "royalblue") + 
  theme(axis.title.y = element_blank(), axis.text.y = element_blank(), axis.ticks.y = element_blank()) +
  scale_y_continuous(expand = c(0,0)) 

# Node #25
# 8 GO terms
data1 <- egoN25@result[1:8, ]
data1$order <- c(1:length(data1$ID))
ggplot(data1, aes(x = order, y = Count, fill = p.adjust)) + 
  geom_bar(stat = "identity") +
  geom_text(aes(label = Description, y = 1), hjust=0, vjust= 0.5, size= 6) +
  coord_flip()  + 
  theme_classic() +
  scale_fill_gradient(low = "orange", high = "royalblue") + 
  theme(axis.title.y = element_blank(), axis.text.y = element_blank(), axis.ticks.y = element_blank()) +
  scale_y_continuous(expand = c(0,0)) 

# Node #26
# 8 GO terms
data1 <- egoN26@result[1:8, ]
data1$order <- c(1:length(data1$ID))
ggplot(data1, aes(x = order, y = Count, fill = p.adjust)) + 
  geom_bar(stat = "identity") +
  geom_text(aes(label = Description, y = 1), hjust=0, vjust= 0.5, size= 6) +
  coord_flip()  + 
  theme_classic() +
  scale_fill_gradient(low = "orange", high = "royalblue") + 
  theme(axis.title.y = element_blank(), axis.text.y = element_blank(), axis.ticks.y = element_blank()) +
  scale_y_continuous(expand = c(0,0)) 

# Node #28
# 8 GO terms
data1 <- egoN28@result[1:8, ]
data1$order <- c(1:length(data1$ID))
ggplot(data1, aes(x = order, y = Count, fill = p.adjust)) + 
  geom_bar(stat = "identity") +
  geom_text(aes(label = Description, y = 1), hjust=0, vjust= 0.5, size= 6) +
  coord_flip()  + 
  theme_classic() +
  scale_fill_gradient(low = "orange", high = "royalblue") + 
  theme(axis.title.y = element_blank(), axis.text.y = element_blank(), axis.ticks.y = element_blank()) +
  scale_y_continuous(expand = c(0,0)) 



#######################  Diffusion maps plot with the color code from the original representation ###############

library(ggplot2)

# Create a data frame with the required information
cluster_names <- dm$clusters
cells_names <- colnames(mat)
data_colours <- data.frame(cluster_names, cells_names)
colours_clusters <- c(sc@fcol[c(1,2,3,4,5,8,9,11,12,18,23)])  
cluster_Names <- as.vector(unique(cluster_names))
cluster_Names <- cluster_Names[c(1,2,5,3,6,7,8,9,10,4,11)]
for (i in 1:length(data_colours$cluster_names)) {
  for (j in 1:length(cluster_Names)) {
    if (data_colours$cluster_names[i] == cluster_Names[j]) {
      data_colours$colour[i] <- colours_clusters[j]    
    }
  }
}

data_colours$DC1 <- dm$DC1
data_colours$DC2 <- dm$DC2

data_colours$sample <- substr(data_colours$cells_names, start = 1, stop = 4)

data_colours$colour <- factor(data_colours$colour, levels = data_colours[match(levels(data_colours$cluster_names), data_colours$cluster_names), "colour"])

# Plotting the DM representation (first 2 DCs)
ggplot(data_colours, aes(x=DC1, y=DC2)) + 
  geom_point(aes(color=cluster_names), alpha= 0.7, size= 0.3) +
  scale_colour_manual(values= levels(data_colours$colour)) + 
  theme_bw() + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.text.x=element_blank(), axis.text.y=element_blank())


############################################################################################
###################   Plotting the DM representation (first 3 DCs)  ########################
############################################################################################

library(rgl)

# Trying to use the same colours as the RaceID object for the dm plotting
cluster_names <- dm$clusters
cells_names <- colnames(mat)
data_colours <- data.frame(cluster_names, cells_names)
colours_clusters <- c(sc@fcol[c(1,2,3,4,5,8,9,11,12,18,23)])
cluster_Names <- as.vector(unique(cluster_names))
cluster_Names <- cluster_Names[c(1,2,5,3,6,7,8,9,10,4,11)]
for (i in 1:length(data_colours$cluster_names)) {
  for (j in 1:length(cluster_Names)) {
    if (data_colours$cluster_names[i] == cluster_Names[j]) {
      data_colours$colour[i] <- colours_clusters[j]
    }
  }
}

data_colours$DC1 <- dm$DC1
data_colours$DC2 <- dm$DC2


my_col <- data_colours$colour

# Generate teh 3D plot
plot3d( 
  x=dm$DC2, y=dm$DC3, z=dm$DC1, 
  col = my_col, 
  type = 's', 
  radius = .001,
  xlab="DC2", ylab="DC3", zlab="DC1",
  box= FALSE,
  axes = TRUE)
